-- Plugins that were ported from my vim configuration. These should be analyzed
-- again and re-evaluated.
return {
  -- { 'unblevable/quick-scope',        event = 'VeryLazy' },
  -- 'justinmk/vim-ipmotion',
  -- 'junegunn/gv.vim',
  -- 'tpope/vim-rhubarb',
  -- 'tpope/vim-repeat',
  -- 'kana/vim-operator-user',
  -- 'mwgkgk/vim-operator-insert',
  -- 'mwgkgk/vim-operator-append',
  -- 'svermeulen/vim-subversive',
  -- 'rickhowe/wrapwidth',
  -- Future plugins... {{{
  -- In case I want to work with GitHub's PR:
  --   pwntester/octo.nvim
  -- More Git plugins
  --   NeogitOrg/neogit
  -- For markdown, not currently working, so debugging is needed.
  --   iamcco/markdown-preview.nvim
  -- Some more:
  --   kevinhwang91/nvim-ufo
  --   SmiteshP/nvim-navic
  --   SmiteshP/nvim-navbuddy
  --   nvim-neotest/neotest
  --   folke/neoconf.nvim
  --   folke/sidekick.nvim
  --   folke/edgy.nvim
  --   linux-cultist/venv-selector.nvim
  -- Future plugins... }}}
}

-- vim: foldmethod=marker
