return {
	["applicaitons"] = "applications",
	["Exercis"] = "Exercise",
	["theer"] = "there",
	["isn"] = "isn",
	["examel"] = "example",
	["implemnted"] = "implemented",
	["rom"] = "rom",
	["avalibale"] = "available",
	["comparing"] = "comparing",
	["byte"] = "byte",
	["info"] = "info",
	["txt"] = "txt",
	["ROM"] = "ROM",
	["buf"] = "buf",
	["nnot"] = "not",
	["tteh"] = "the",
	["printf"] = "printf",
	["chaging"] = "changing",
	["implemneted"] = "implemented",
	["shouldn"] = "shouldn",
	["doesn"] = "doesn",
	["fn"] = "fn",
}
